defaults:
  - _self_

llm:
  api_key: ${oc.env:OPENAI_API_KEY}

  embeddings:
    model: text-embedding-3-small
    chunk_size: 1000
    chunk_overlap: 200

  completions:
    model: gpt-4o-mini
    temperature: 1.0

tree:
  hyperparams:
    n_branches: 3
    n_queries: 2
    n_results: 5
    n_iterations: 5

  flag:
    use_cache: false
    use_tools: false

paths:
  project_root: ${hydra:runtime.cwd}
  data_dir: ${paths.project_root}/data
  database_dir: ${paths.project_root}/database
