defaults:
  - _self_

llm:
  api_key: ${oc.env:OPENAI_API_KEY}

  embeddings:
    model: text-embedding-3-small
    chunk_size: 1000
    chunk_overlap: 200

  completions:
    model: gpt-4o-mini
    temperature: 1.0

tree:
  hyperparams:
    n_branches: 3
    n_queries: 2
    n_results: 5
    n_iterations: 5

  # Hybrid retrieval settings
  retrieval:
    use_hybrid: true
    dense_weight: 0.7
    sparse_weight: 0.3
    fusion_method: "rrf" # "rrf", "weighted", "parallel"
    bm25_k1: 1.2
    bm25_b: 0.75
    rrf_k: 60

  # Web search settings
  web_search:
    timeout_seconds: 15
    max_retries: 2
    retry_delay: 5
    region: "vn-vi" # Vietnamese region
    time_filter: "y" # Past year
    enable_fallback: true

paths:
  project_root: .
  data_dir: ./data
  database_dir: ./database
